# The URL the site will be built for
base_url = "http://127.0.0.1:1111"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[extra]
title = "Energetický report"
price = "Za 95.000 Kč bez DPH získáte úvodní analýzu energetického auditu, pět mobilních IoT zařízení (každé se 3 neinvazivními proudovými senzory) včetně instalace u vás a roční konektivitu a provoz aplikace Microsoft Power BI."


[[extra.benefits]]
image = "/energy_report/static/images/effectivity.svg"
alt = "Efektivnost"
title = "Mobilní řešení"
description = "Zcela mobilní řešení, které je kdykoliv snadno přenositelné na další stroje ve vašem podniku."

[[extra.benefits]]
image = "/energy_report/static/images/consumption.svg"
alt = "Spotřeba"
title = "Bezpečná komunikace"
description = "Zařízení komunikují bezdrátově a nezávisle na vaší interní síti."

[[extra.benefits]]
image = "/energy_report/static/images/document.svg"
alt = "Dokument"
title = "Data v Microsoft Power BI"
description = "Přehledné reporty o spotřebě strojů najdete v aplikaci Microsoft Power BI."


[[extra.steps]]
number = "1"
title = "Online schůzka"
description = "Vyplňte formulář níže, ozveme se vám a společně domluvíme termín online schůzky. Na ní probereme, jak program funguje, vaše dotazy a společně vybereme jak budeme spotřebu monitorovat."

[[extra.steps]]
number = "2"
title = " Nasazení - zahájení pilotu"
description = "Do 30 dnů u vás senzory nainstalujeme a integrujeme je s vybranými aplikacemi. Instalace zabere jen pár desítek minut a okamžitě budete mít k dispozici data o spotřebě energií."
button = "Zobrazit ukázku reportu"

[[extra.steps]]
number = "3"
title = "Sledování a vyhodnocení"
description = "Data o spotřebě budete mít okamžitě ve svém počítači i telefonu. Společně se na data podíváme, vyhodnotíme přínosy a pobavíme se o dalších možnostech nasazení a rozšíření IoT monitoringu."


[[extra.features]]
image = "/energy_report/static/images/efectivity.svg"
alt = "Efektivita"
title = "Rychle a bezstarostně"
description = "Instalaci začneme do 30 dnů a potrvá jen desítky minut. Provoz omezíme minimálně, nebo vůbec."

[[extra.features]]
image = "/energy_report/static/images/consumption.svg"
alt = "Spotřeba"
title = "Okamžitá data z provozu"
description = "Ihned po instalaci uvidíte data z výroby ve vašem telefonu i počítači."

[[extra.features]]
image = "/energy_report/static/images/document.svg"
alt = "Dokument"
title = "Záruka spokojenosti"
description = "Pokud nebudete spokojeni, můžete nám zařízení do 100 dnů vrátit."


[[extra.faqs]]
question = "Jak probíhá program energeticky.report?"
answer = "Po odeslání formuláře vás kontaktujeme a domluvíme se na termínu společné online schůzky. Cílem je zodpovědět vaše dotazy a vybrat způsob měření spotřeby energií."

[[extra.faqs]]
question = "Je možné pilot rozšířit o další zařízení?"
answer = "Ano, cena každého dalšího zařízení je 9 500 Kč bez DPH."

[[extra.faqs]]
question = "Jak data o výrobě přenášíte? Je to bezpečné?"
answer = "Data přenášíme bezdrátovými sítěmi NB-IoT a LTE-M. Mají skvělé pokrytí včetně vnitřních prostor továren. Síť je zcela nezávislá od vaší interní sítě, přenos je zabezpečený."

[[extra.faqs]]
question = "Kde uvidíme data?"
answer = "V programu energeticky.report pracujeme s výstupy v Power BI od Microsoftu. Jak to může vypadat se podívejte na odkaze. Pokud však potřebujete data vidět jinde, najdeme cestu, jak to udělat. S pomocí našich partnerů pak nabízíme také vlastní webové aplikace."

[[extra.faqs]]
question = "Kolik budeme platit za služby po skončení předplaceného roku?"
answer = "Měsíční poplatek za jedno IoT zařízení po uplynutí přeplaceného 1. roku bude 190 Kč bez DPH."

